version: '3'

services:

    nginx:
        container_name: nginx
        image: nginx:1
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        volumes:
            - ../:/app
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf


    php:
        container_name: php
        build:
            context: php
            args:
                uid: 1000
                gid: 1000
        volumes:
            - ../:/app
        working_dir: /app
        links:
            - db

    db:
        container_name: db
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "supersicher"
            MYSQL_USER: "maxim"
            MYSQL_PASSWORD: "maxim_password"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        container_name: phpma
        image: phpmyadmin:5
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1

volumes:
    mysql_data: